### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by mojzesh** [sssuneeth/Next-mantine-pricing-component#2]
Hey @tokitouq!

Great work! ⭐️

May I know what is the license for this repo ?

Thanks in advance!

**Comment by stabldev** [comment]
Hi @mojzesh, sorry for late reply.

> May I know what is the license for this repo ?

There are no licenses. I did this to practice my skills.
You can use it however you want :)

> Great work! ⭐️

Thank you :heart:

**Comment by mojzesh** [comment]
Great!

Thanks for clarification :)

ps. I would suggest adding below then :D, but that's up to you :)
https://choosealicense.com/licenses/wtfpl/

Cheers!

**Comment by stabldev** [comment]
Oh! sounds great XD
Thanks for the suggestion :D

Have a nice day!
**closing this...
